name: Chromatic Visual Testing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  chromatic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up pnpm
        run: npm install -g pnpm  # Install pnpm globally

      - name: Verify pnpm installation
        run: pnpm --version  # Check if pnpm is correctly installed

      - name: List scripts in package.json
        run: cat package.json | jq '.scripts' # This will output the scripts section of your package.json so you can verify that build-storybook is there


      - name: Install dependencies
        run: pnpm install
      
      - name: Build Storybook
        run: |
          cd apps/docs
          pnpm run build-storybook  # This will now use the script inside apps/docs

      - name: Run Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: secrets.CHROMATIC_TOKEN
        env:
          CHROMATIC_TOKEN: secrets.CHROMATIC_TOKEN
